version: '3'
services:
  backend:
    image: backend:latest
    container_name: backend
    env_file:
      - ./backend/backend.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    env_file:
      - ./backend/backend.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  frontend:
    image: frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./front/frontend.env
    networks:
      - app-network

volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge
